### ISSUE TITLE
 Am I missing an assembly reference?

### ISSUE THREAD

**Issue by iBicha** [aras-p/ToyPathTracer#1]
Even though Burst is installed in the package manager, something is missing
`/Users/ibicha/Library/Unity/cache/packages/staging-packages.unity.com/com.unity.burst@0.2.3/Editor/BurstReflection.cs(19,67): error CS0246: The type or namespace name `AssembliesType' could not be found. Are you missing an assembly reference?`
(Yes this is probably related to the package manager, not the path tracer itself I guess)

**Comment by aras-p** [comment]
I think this version of Burst needs a very specific Unity build. Make sure you're using the one linked to from repo readme (it should be 2018.1 beta 12, but at version `ed1bf90b40e6` - can see that in your About dialog by pressing Alt IIRC). You might have a slightly earlier build that was still called b12.

**Comment by iBicha** [comment]
I see, I am on b12, but `b4ca90bad6b1`. Thanks for clearing that up!

**Comment by aras-p** [comment]
Yeah I ran into that myself during upgrade of Burst package. Life on the bleeding edge of builds :)
