### ISSUE TITLE
How do you run/update the numbers on Mono?

### ISSUE THREAD

**Issue by migueldeicaza** [aras-p/ToyPathTracer#3]
Hello Aras,

How are you running/updating the numbers in Mono, as there is no MathF there yet.

I did a port from MathF to the DesktopCLR API, which is supported in Mono, and put my changes here:

https://github.com/migueldeicaza/ToyPathTracer/tree/desktop-clr

The odd thing is that on my system, .NET Core 2.1.4 seems slower, perhaps we have different versions?   

```
$ dotnet --version
2.1.4
$ mono --version
Mono JIT compiler version 5.13.0 (master/4723e6603e6 Sun Apr  1 21:34:34 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
$ dotnet run
2752.30ms 4.2Mrays/s 11.47Mrays/frame frames 1
^c
$ mono demo.exe
1819.82ms 6.3Mrays/s 11.47Mrays/frame frames 1
^c
$ mono -O=float32 demo.exe
1462.56ms 7.8Mrays/s 11.47Mrays/frame frames 1
^c
$
```

That said, to make it more apples to apples, I just submitted a pull request to Mono to get MathF:

https://github.com/mono/mono/pull/7941

With that patch, I can compare apples of the same species, and now I get:

```
$ dotnet run
2876.87ms 4.1Mrays/s 11.76Mrays/frame frames 1
2874.08ms 4.1Mrays/s 11.76Mrays/frame frames 2
2876.00ms 4.1Mrays/s 11.76Mrays/frame frames 3
2860.35ms 4.1Mrays/s 11.76Mrays/frame frames 4
2852.96ms 4.1Mrays/s 11.75Mrays/frame frames 5
2842.87ms 4.1Mrays/s 11.76Mrays/frame frames 6
2840.46ms 4.1Mrays/s 11.76Mrays/frame frames 7
2835.01ms 4.1Mrays/s 11.76Mrays/frame frames 8
2829.51ms 4.2Mrays/s 11.76Mrays/frame frames 9
2829.30ms 4.2Mrays/s 11.75Mrays/frame frames 10
2833.15ms 4.2Mrays/s 11.76Mrays/frame frames 11
2831.47ms 4.2Mrays/s 11.76Mrays/frame frames 12
2841.67ms 4.1Mrays/s 11.76Mrays/frame frames 13
2851.48ms 4.1Mrays/s 11.76Mrays/frame frames 14
2857.88ms 4.1Mrays/s 11.76Mrays/frame frames 15
2881.28ms 4.1Mrays/s 11.75Mrays/frame frames 16
2888.21ms 4.1Mrays/s 11.76Mrays/frame frames 17
2894.16ms 4.1Mrays/s 11.76Mrays/frame frames 18
2896.44ms 4.1Mrays/s 11.75Mrays/frame frames 19
2904.69ms 4.0Mrays/s 11.76Mrays/frame frames 20
2937.43ms 4.0Mrays/s 11.76Mrays/frame frames 21
2936.99ms 4.0Mrays/s 11.76Mrays/frame frames 22
2937.48ms 4.0Mrays/s 11.76Mrays/frame frames 23
2935.11ms 4.0Mrays/s 11.76Mrays/frame frames 24
2933.07ms 4.0Mrays/s 11.76Mrays/frame frames 25
2932.50ms 4.0Mrays/s 11.76Mrays/frame frames 26
2928.50ms 4.0Mrays/s 11.76Mrays/frame frames 27
2928.81ms 4.0Mrays/s 11.76Mrays/frame frames 28
2927.48ms 4.0Mrays/s 11.76Mrays/frame frames 29
2925.44ms 4.0Mrays/s 11.76Mrays/frame frames 30
$ mono mathf.exe
1815.47ms 6.5Mrays/s 11.76Mrays/frame frames 1
1825.87ms 6.4Mrays/s 11.76Mrays/frame frames 2
1813.91ms 6.5Mrays/s 11.76Mrays/frame frames 3
1836.47ms 6.4Mrays/s 11.76Mrays/frame frames 4
1849.84ms 6.4Mrays/s 11.75Mrays/frame frames 5
1843.00ms 6.4Mrays/s 11.76Mrays/frame frames 6
1870.65ms 6.3Mrays/s 11.76Mrays/frame frames 7
1873.14ms 6.3Mrays/s 11.76Mrays/frame frames 8
1871.27ms 6.3Mrays/s 11.76Mrays/frame frames 9
1873.10ms 6.3Mrays/s 11.75Mrays/frame frames 10
1871.02ms 6.3Mrays/s 11.76Mrays/frame frames 11
1868.86ms 6.3Mrays/s 11.76Mrays/frame frames 12
1870.36ms 6.3Mrays/s 11.76Mrays/frame frames 13
1872.45ms 6.3Mrays/s 11.76Mrays/frame frames 14
1871.38ms 6.3Mrays/s 11.76Mrays/frame frames 15
1870.67ms 6.3Mrays/s 11.76Mrays/frame frames 16
1873.83ms 6.3Mrays/s 11.76Mrays/frame frames 17
1876.38ms 6.3Mrays/s 11.76Mrays/frame frames 18
1878.16ms 6.3Mrays/s 11.75Mrays/frame frames 19
1879.80ms 6.3Mrays/s 11.76Mrays/frame frames 20
1880.18ms 6.3Mrays/s 11.76Mrays/frame frames 21
1882.34ms 6.2Mrays/s 11.76Mrays/frame frames 22
1878.91ms 6.3Mrays/s 11.76Mrays/frame frames 23
1880.97ms 6.3Mrays/s 11.76Mrays/frame frames 24
1879.36ms 6.3Mrays/s 11.76Mrays/frame frames 25
1879.97ms 6.3Mrays/s 11.76Mrays/frame frames 26
1878.91ms 6.3Mrays/s 11.76Mrays/frame frames 27
1878.21ms 6.3Mrays/s 11.76Mrays/frame frames 28
1879.25ms 6.3Mrays/s 11.76Mrays/frame frames 29
1879.26ms 6.3Mrays/s 11.76Mrays/frame frames 30
$ mono -O=float32 mathf.exe
1633.95ms 7.2Mrays/s 11.76Mrays/frame frames 1
1545.29ms 7.6Mrays/s 11.76Mrays/frame frames 2
1509.87ms 7.8Mrays/s 11.76Mrays/frame frames 3
1550.70ms 7.6Mrays/s 11.76Mrays/frame frames 4
1565.38ms 7.5Mrays/s 11.75Mrays/frame frames 5
1551.46ms 7.6Mrays/s 11.76Mrays/frame frames 6
1567.24ms 7.5Mrays/s 11.76Mrays/frame frames 7
1579.61ms 7.4Mrays/s 11.76Mrays/frame frames 8
1565.49ms 7.5Mrays/s 11.76Mrays/frame frames 9
1558.81ms 7.5Mrays/s 11.75Mrays/frame frames 10
1570.96ms 7.5Mrays/s 11.76Mrays/frame frames 11
1583.83ms 7.4Mrays/s 11.76Mrays/frame frames 12
1587.42ms 7.4Mrays/s 11.76Mrays/frame frames 13
1590.42ms 7.4Mrays/s 11.76Mrays/frame frames 14
1596.51ms 7.4Mrays/s 11.76Mrays/frame frames 15
1596.27ms 7.4Mrays/s 11.75Mrays/frame frames 16
1591.59ms 7.4Mrays/s 11.76Mrays/frame frames 17
1591.84ms 7.4Mrays/s 11.76Mrays/frame frames 18
1585.52ms 7.4Mrays/s 11.75Mrays/frame frames 19
1578.45ms 7.4Mrays/s 11.76Mrays/frame frames 20
1575.85ms 7.5Mrays/s 11.76Mrays/frame frames 21
1571.86ms 7.5Mrays/s 11.76Mrays/frame frames 22
1568.69ms 7.5Mrays/s 11.76Mrays/frame frames 23
1565.06ms 7.5Mrays/s 11.76Mrays/frame frames 24
1562.82ms 7.5Mrays/s 11.76Mrays/frame frames 25
1560.53ms 7.5Mrays/s 11.76Mrays/frame frames 26
1558.02ms 7.5Mrays/s 11.76Mrays/frame frames 27
1555.59ms 7.6Mrays/s 11.76Mrays/frame frames 28
1554.55ms 7.6Mrays/s 11.76Mrays/frame frames 29
1552.10ms 7.6Mrays/s 11.76Mrays/frame frames 30
```

**Comment by xoofx** [comment]
@migueldeicaza you need to run with release `dotnet run --framework netcoreapp2.0 -c Release` otherwise everything is running with debug for .NET Core and it is uber slow!  😛 With Release, you should get a x5 speedup compare to Mono (with or without `-o=float32`)

**Comment by xoofx** [comment]
Note, I have added multitargeting to add `net461` FW moniker as part of PR #4 to make it possible to compile with dotnet build and run with mono

**Comment by aras-p** [comment]
@migueldeicaza I just ran from VS Mac, with Release config and without debugging. Don't know what exactly it ends up doing, will investigate.

**Comment by migueldeicaza** [comment]
Thanks xoofx!   That does explain the difference!

**Comment by migueldeicaza** [comment]
Another surprising side effect: code compiled with Roslyn, running on Mono/float32 runs at 6.6, while the same code compiled with mcs, runs at 7.3

**Comment by aras-p** [comment]
Ok, phew, so I did not do a gross mis-representation of Mono; it is close to 3x slower on this particular workload than .NET Core. I'll add a note on float32 & LLVM options to the post.

Why is 32 bit floating point not the default by the way? (my guess would be on a "it's a long story...", which is fine :))

**Comment by migueldeicaza** [comment]
It is a long story - let me write a blog post for posterity, I can not let you have all the fun!

**Comment by migueldeicaza** [comment]
Ok, this has turned out to be a good exercise!

Our LLVM support was still doing 32->64 casts, so we were not really getting the full gains of 32-bit float when using LLVM!

So we just fixed that too.  And we also increased the inline limit ([pending pull request](https://github.com/mono/mono/pull/8141)) that is more suitable for LLVM. 

The current inline limit was suitable for Mono's JIT compiler, but it was too small for LLVM, so this is closer to C++.   The value currently can be tuned by hand using the `MONO_INLINE_LIMIT` environment variable).

This is running on a different computer, so I can not compare apples/apples against the above, but the results are now as follows:

| Runtime  | Results  |
|---|--:|
| dotnet -c Release  | 18.3Mray/sec  |
| mono --llvm -O=float32  | 12.4Mray/sec  |
| MONO_INLINELIMIT=100 mono --llvm -O=float32  | 22.5Mray/sec  |

**Comment by migueldeicaza** [comment]
Ok, just got home, and got numbers for the same machine that I originally tested on.

The `.NET Core -c Release` numbers do not match the original results, they are slightly better, but I did reboot the machine since then, so probably something changed in my environment.   

So in this one, I am testing .NET Core 2.1.4 and both Mono/master that includes the LLVM float32 support, and that one with more aggressive inlining:

| Runtime  | Results  |
|---|--:|
| dotnet -c Release  | 21.0Mray/sec  |
| mono --llvm -O=float32  | 16.0Mray/sec  |
| MONO_INLINELIMIT=100 mono --llvm -O=float32  | 29.1Mray/sec  |

**Comment by migueldeicaza** [comment]
Blogged the story of float32 and the numbers:

http://tirania.org/blog/archive/2018/Apr-11.html

**Comment by aras-p** [comment]
I just wrote an update to Mono performance tweaks, including link to your blog post here: http://aras-p.info/blog/2018/04/16/Daily-Pathtracer-10-Update-CsharpGPU/

Will close this issue; thanks for the investigation & suggestions!
